language: ruby
cache: bundler
rvm:
- 2.1

before_script:
- bundle update

script: "bundle exec rake test"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

branches:
  only:
    - gh-pages
    - /^feature-.*$/