# Site settings
title: ACAIS 2016

email: symposium@svcognac.nl
description: > #The 8th Annual CognAC Artificial Intelligence symposium, ACAIS, focusses on Healthcare. How does AI influence healthcare? How can AI improve the care that we receive?  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://acais.nl" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

hide_venue: false
hide_feature_overview: false
TBA_modus: false

permalink: pretty

exclude: [vendor] # for travis