# Site settings
title: ACAIS 2017

email: symposium@svcognac.nl
description: > #The 10th Annual CognAC Artificial Intelligence symposium, ACAIS, focusses on Survival. How does AI influence survival? How can AI improve it?  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://acais.nl" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

hide_venue: true
hide_feature_overview: true
TBA_modus: false

permalink: pretty

exclude: [vendor] # for travis

gems:
- jekyll-redirect-from