# Site settings
title: ACAIS 2018

email: symposium@svcognac.nl
description: > #The 10th Annual CognAC Artificial Intelligence symposium, ACAIS, focusses on Survival. How does AI influence survival? How can AI improve it?  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://acais.nl" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

hide_venue: false
hide_feature_overview: false
TBA_modus: false
STD_modus: false
full_modus: true
can_order_tickets: true

permalink: pretty

exclude: [vendor] # for travis

gems:
- jekyll-redirect-from